# This is a basic workflow to help you get started with Actions

name: Public HTML

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      - name: Build
        run: |
          npm ci
          npm run build

      - name: Configure git user
        run: |
          hub config --global user.name "github-actions[bot]"
          hub config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Push
        run: |
          cd public_html
          hub init -b public_html
          hub add .
          hub commit -m "Build public_html [Github actions]"
          echo hub remote add output https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          hub remote add output https://${GITHUB_ACTOR}:${{ secrets.GITHUB_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git
          hub push -fu output public_html

