# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test CI

# Run on basicly every change to the tree
on:
  push:
    branches: ["**"]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        uses: actions/checkout@v2

      # Sets up node environment
      - name: Use Node.js 17
        uses: actions/setup-node@v2
        with:
          node-version: '17'

      # Install node modules
      - name: Install node modules
        run: |
          npm ci

      # Attempt to build
      - name: Build module
        run: |
          npm run build --if-present

      # Run tests
      - name: Run test suite
        run: |
          npm run test --if-present
